Repository ktwrd/beans-rs, pull requests merged in 2024-06, with the labels that each got.

#3 Only initialize sentry in release builds
  src/main.rs
Labels: bug

#7 v1.4.0 - QoL and stability improvements.
  .config/beans/mod_name.txt
  .config/beans/mod_name_short.txt
  .config/beans/remote_url_base.txt
  .config/beans/version_url.txt
  .github/workflows/compile.yml
  .github/workflows/release.yml
  Binaries/7z.dll
  Binaries/7z.so
  Binaries/c7zip.dll
  Binaries/libc7zip.so
  Cargo.toml
  README.md
  src/appvar.json
  src/appvar.rs
  src/butler.rs
  src/ctx.rs
  src/depends.rs
  src/error.rs
  src/flags.rs
  src/helper/linux.rs
  src/helper/mod.rs
  src/helper/windows.rs
  src/lib.rs
  src/logger.rs
  src/main.rs
  src/text/install_complete_linux.txt
  src/text/install_complete_windows.txt
  src/text/msgbox_panic_text.txt
  src/version.rs
  src/wizard.rs
  src/workflows/install.rs
  src/workflows/update.rs
  src/workflows/verify.rs
  working commands.md
Labels: enhancement, new release

#9 v1.4.1 - Bug Fix
  Cargo.toml
  src/helper/mod.rs
Labels: new release

#10 v1.4.2 - Bug Fixes
  Cargo.toml
  src/helper/mod.rs
  src/workflows/update.rs
  src/workflows/verify.rs
Labels: bug, new release
